### ISSUE TITLE
why doesn't work on the colab either else enviroment based on cloud?

### ISSUE THREAD

**Issue by mi4da** [microsoft/TextWorld#304]
env_id = textworld.gym.register_game("/tw_games/custom_game.z8",max_episode_steps=50)
env = gym.make(env_id)  # Start the environment.
>>> action space does not inherit from `gym.spaces.Space`, actual type: <class 'NoneType'>
???

**Comment by MarcCote** [comment]
Hi @mi4da, I have fixed that issue in the master branch (see [fix](https://github.com/microsoft/TextWorld/pull/303/files#diff-7fd7a0aa22cc40d7de24617ac188d3da89c6e7b6e9282693781924375dedda4fL89)) but haven't made a release yet. However, I do have a prerelease that should work. Can you try installing it?
`pip install --pre textworld`

**Comment by mi4da** [comment]
Well, Thanks for the reply! I had just done it as you say, and I tested the compatibility between the different versions of gym and textworld and also the type of game files, then I find it still doesn't work with lasted gym, you could review it in this notebook: https://colab.research.google.com/drive/1J5MlwJCjKJX9qjqqvaf-XqG-gj0Is_mg?usp=sharing

**Comment by mi4da** [comment]
> Hi @mi4da, I have fixed that issue in the master branch (see [fix](https://github.com/microsoft/TextWorld/pull/303/files#diff-7fd7a0aa22cc40d7de24617ac188d3da89c6e7b6e9282693781924375dedda4fL89)) but haven't made a release yet. However, I do have a prerelease that should work. Can you try installing it? `pip install --pre textworld`

Well, Thanks for the reply! I had just done it as you say, and I tested the compatibility between the different versions of gym and textworld and also the type of game files, then I find it still doesn't work with lasted gym, you could review it in this notebook: https://colab.research.google.com/drive/1J5MlwJCjKJX9qjqqvaf-XqG-gj0Is_mg?usp=sharing

**Comment by MarcCote** [comment]
TextWorld 1.5.3 has been released on PyPI.

Feel free to reopen this issue if you encounter any other issues with running TextWorld in Colab.
